dostawy/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('okulickiego/', include('okulickiego.urls')),
    path('rudna/', include('rudna.urls')),
    path('armii/', include('armii.urls')),
    path('wola/', include('wola.urls')),
    path('rzecha/', include('rzecha.urls')),
    path('sikorskiego/', include('sikorskiego.urls')),
    path('ostrow/', include('ostrow.urls')),
    path('lezajsk/', include('lezajsk.urls')),
    path('jaroslaw/', include('jaroslaw.urls')),
    path('podkarpacka/', include('podkarpacka.urls')),
    path('jasionka/', include('jasionka.urls')),
    path('warszawska/', include('warszawska.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('register.urls')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon/favicon.ico'))),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lezajsk/urls.py
from django.urls import path, include
from .views import licz_list, handle_licz, dostawy_list, dostawy_details, edit_dostawy, LicznikBazowyLezajskViewSet
from rest_framework import routers
from .api import UserAuthentication


router = routers.DefaultRouter()
router.register(r'liczniki', LicznikBazowyLezajskViewSet)


app_name = "lezajsk"
urlpatterns = [
    path('liczniki/', licz_list, name="liczniki"),
    path('dost/', dostawy_list, name="dost_lezajsk"),
    path('api/', include(router.urls)),
    path('api/auth/', UserAuthentication.as_view(), name="UserAuth"),
    path('liczniki/add/', handle_licz, name="add_liczniki"),
    path('dost/<int:stany_id>/', dostawy_details, name="details_dost"),
    path('dost/<int:stany_id>/edit/', edit_dostawy, name="edit_dost"),
]

main/urls.py
from django.urls import path
from .views import home, about, contact, user_profile


urlpatterns = [
    path('', home, name="home"),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('user/<int:user_id>/profile/', user_profile, name='userprofile'),
]

lezajsk/models.py
from django.db import models
from common.models import LicznikBaza, PaliwoDostAbst, Dostawcy, DaneStacji


class DaneStacjiLezajsk(DaneStacji):

    def __str__(self):
        return f'{self.skr_nazwa}'


class LicznikBazowyLezajsk(LicznikBaza):

    def __str__(self):
        return f'{self.ARTYKUL}'


class DostawaLezajsk(PaliwoDostAbst):
    dostawca = models.ForeignKey(Dostawcy, on_delete=models.CASCADE, related_name='dost_lezajsk')


class LicznikDostawyLezajsk(LicznikBaza):
    number = models.ForeignKey(DostawaLezajsk, on_delete=models.CASCADE, related_name='dost_licz_lezajsk')

    def __str__(self):
        return f'{self.number}'

lezajsk/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit
from django import forms
from .models import DostawaLezajsk


class StanPaliwSaveForm(forms.ModelForm):
    class Meta:
        model = DostawaLezajsk
        fields = ['dostawca', 'number', 'zb_98', 'zb_95', 'zb_on', 'zb_ontir', 'zb_lpg', 'zb_adblue']
        labels = {
                    "dostawca": 'Dostawca',
                    "number": "Numer Dostawy",
                    "zb_98": "Pb98",
                    "zb_95": "Pb95",
                    "zb_on": "ON",
                    "zb_ontir": "ON TIR",
                    "zb_lpg": "LPG",
                    "zb_adblue": "Ad Blue"
                }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit("stan_save", "Zapisz"))
        # self.helper.add_input(Submit('stan_cancel', 'Anuluj', css_class='btn btn-secondary'))
        self.fields['number'].widget.attrs['readonly'] = True
        self.helper.layout = Layout(
            Fieldset(
                'Zapisz Dostawę',
                'number',
                'dostawca',
                'zb_98',
                'zb_95',
                'zb_on',
                'zb_ontir',
                'zb_lpg',
                'zb_adblue',

            ),
            Fieldset(
                ' '
            )
        )

lezajsk/views.py
from rest_framework import viewsets, permissions
from .serializers import LicznikBazowyLezajskSerializer
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.core.paginator import Paginator
from .forms import StanPaliwSaveForm
from django.contrib.auth.decorators import login_required, permission_required
from .models import DostawaLezajsk, LicznikDostawyLezajsk, LicznikBazowyLezajsk, DaneStacjiLezajsk
from django.contrib import messages
from common.untils import send_my_email, send_my_email_modified


@login_required
@permission_required('lezajsk.view_licznikbazowylezajsk')
def licz_list(request):
    if request.user.is_authenticated:
        liczniki = LicznikBazowyLezajsk.objects.order_by("ID_DYS", "ID_WAZ")
        q = request.GET.get("qre")
        if q:
            liczniki = liczniki.filter(SYMBOL__icontains=q)

        return render(request, 'lezajsk/liczniki.html', {"liczniki": liczniki})
    return redirect(reverse('login'))


@login_required
@permission_required('lezajsk.view_dostawalezajsk')
def dostawy_list(request):
    if request.user.is_authenticated:
        lista = DostawaLezajsk.objects.all().order_by('-number')
        paginator = Paginator(lista, 12)
        page_number = request.GET.get('page')
        lista_dost = paginator.get_page(page_number)
        return render(request, 'lezajsk/list_dostawy.html', {'lista': lista_dost})
    return redirect(reverse('login'))


@login_required
@permission_required('lezajsk.view_dostawalezajsk')#, raise_exception=True)
def dostawy_details(request, stany_id):
    if request.user.is_authenticated:
        stan = DostawaLezajsk.objects.get(number=stany_id)
        created = stan.created.ctime()
        modified = stan.modified.ctime()
        liczniki = LicznikDostawyLezajsk.objects.filter(number=stany_id).order_by("ID_DYS", "ID_WAZ")
        q = request.GET.get("qre")
        if q:
            liczniki = liczniki.filter(SYMBOL__icontains=q)
        context = {'stan': stan, 'liczniki': liczniki, 'created': created, 'modified': modified}
        return render(request, 'lezajsk/dostawy_details.html', context)
    return redirect(reverse('login'))


@login_required
@permission_required('lezajsk.change_dostawalezajsk')
def edit_dostawy(request, stany_id):
    if request.user.is_authenticated:
        user = request.user
        name_stacji = get_object_or_404(DaneStacjiLezajsk)
        dostawa = get_object_or_404(DostawaLezajsk, pk=stany_id)
        liczniki = LicznikDostawyLezajsk.objects.filter(number=stany_id).order_by("ID_DYS", "ID_WAZ")
        if request.method == "POST":
            form = StanPaliwSaveForm(request.POST, instance=dostawa)
            if form.is_valid():
                form.save()
                messages.success(request, 'Poprawa dostawa została zapisana w bazie.')
                try:
                    send_my_email_modified(dostawa.number, user.first_name, name_stacji)
                    messages.success(request, 'Powiadomienie edycji dostawy zostało wysłane na email.')

                except:
                    messages.warning(request, 'Powiadomienie edycji dostawy nie zostało wysłane na email.')
            return HttpResponseRedirect(reverse("lezajsk:dost_lezajsk"))
        else:
            form = StanPaliwSaveForm(instance=dostawa)
        context = {'lista': dostawa, 'liczniki': liczniki, 'form': form}
        return render(request, 'lezajsk/liczniki_add.html', context)
    return redirect(reverse('login'))


@login_required
@permission_required('lezajsk.add_dostawalezajsk')
def handle_licz(request):
    if request.user.is_authenticated:
        liczniki = LicznikBazowyLezajsk.objects.order_by("ID_DYS", "ID_WAZ")
        num = DostawaLezajsk.objects.last()
        name_stacji = get_object_or_404(DaneStacjiLezajsk)
        lista = []
        if not num:
            num = 1
        else:
            num = num.number + 1
        form_st = StanPaliwSaveForm(initial={'number': num})
        user = request.user
        if request.method == 'POST':
            if user.is_authenticated:
                if request.POST.get('stan_save'):
                    form_st.helper.form_action = reverse("lezajsk:add_liczniki")
                    form_st = StanPaliwSaveForm(request.POST)
                    if form_st.is_valid():
                        form_st.save()
                        lista = DostawaLezajsk.objects.get(number=num)
                        for licz in liczniki:
                            LicznikDostawyLezajsk.objects.create(ID_DYS=licz.ID_DYS,
                                                                     ID_WAZ=licz.ID_WAZ,
                                                                     SYMBOL=licz.SYMBOL,
                                                                     TOTAL=licz.TOTAL,
                                                                     ARTYKUL=licz.ARTYKUL,
                                                                     KIEDY=licz.KIEDY,
                                                                     KIEDY_WGR=licz.KIEDY_WGR,
                                                                     number=lista)
                        messages.success(request, 'Dostawa została zapisana w bazie.')
                        try:
                            send_my_email(lista.dostawca, user.first_name, name_stacji)
                            messages.success(request, 'Powiadomienie dodania dostawy zostało wysłane na email.')
                        except:
                            messages.warning(request, 'Powiadomienie dodania dostawy nie zostało wysłane na email.')
                    return HttpResponseRedirect(reverse("lezajsk:dost_lezajsk"))

            return redirect(reverse('login'))
        context = {'lista': lista, 'liczniki': liczniki, 'form': form_st}
        return render(request, 'lezajsk/liczniki_add.html', context)
    return redirect(reverse('login'))


class LicznikBazowyLezajskViewSet(viewsets.ModelViewSet):
    queryset = LicznikBazowyLezajsk.objects.all()
    serializer_class = LicznikBazowyLezajskSerializer
    permission_classes = [permissions.DjangoModelPermissions, permissions.IsAuthenticated]
    # authentication_classes = [permissions.IsAuthenticated]

lezajsk/templates/lezajsk/base2.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{% endblock %}
{% block styles %}{% endblock %}
{% block nav %}
<li><a class="nav-link px-2 link-secondary" href="{% url 'home' %}">Lista Stacji</a></li>
<li><a class="nav-link px-2 link-secondary {% if request.resolver_match.view_name == 'lezajsk:dost_lezajsk' %}
link-dark{% endif %}" href="{% url 'lezajsk:dost_lezajsk' %}">Lista Dostaw</a></li>
<li><a class="nav-link px-2 link-secondary {% if request.resolver_match.view_name == 'lezajsk:liczniki' %}
link-dark{% endif %}" href="{% url 'lezajsk:liczniki' %}">Nowa dostawa</a></li>
{% endblock %}
{% block content %}
{% endblock %}

lezajsk/templates/lezajsk/dostawy_details.html
{% extends 'lezajsk/base2.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block styles %}{% endblock %}
{% block title %}Dostawa{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-mb-between py-3 mb-2 border-bottom">
                <h2 class="d-flex">Dostawa {{ stan.created | date:"j E Y H:i:s"}} Leżajsk - ({{stan.dostawca}})</h2>
                {% if created != modified %}
                    <h3 class="d-flex">Zmodyfikowane {{ stan.modified | date:"j E Y H:i:s" }}</h3>
                {% endif %}
            </div>
            <div class="mb-3 border-bottom">
                <a type="button" class="btn btn-primary mb-2" href="{% url 'lezajsk:edit_dost' stan.number %}">Edytuj</a>
            </div>

            <table class="table table-sm table-striped">
                <tr>
                    <th>PB98</th>
                    <td>{{ stan.zb_98 }}</td>
                </tr>
                <tr>
                    <th>PB95</th>
                    <td>{{ stan.zb_95 }}</td>
                </tr>
                <tr>
                    <th>ON</th>
                    <td>{{ stan.zb_on }}</td>
                </tr>
                <tr>
                    <th>ON TIR</th>
                    <td>{{ stan.zb_ontir }}</td>
                </tr>
                <tr>
                    <th>LPG</th>
                    <td>{{ stan.zb_lpg }}</td>
                </tr>
                <tr>
                    <th>ADBLUE</th>
                    <td>{{ stan.zb_adblue }}</td>
                </tr>

            </table>

        </div>
    </div>
    <form>
        <input type="text" id="qq" name="qre">
        <input type="submit" value="Filtruj liczniki" class="btn btn-outline-primary"
               data-bs-toggle="tooltip" data-bs-placement="bottom" title="Filtrowanie po symbolu">
    </form>
    <div>
        <table class="table table-sm table-striped">
            <thead>
                <tr>
                    <th>NUMER DYST</th>
                    <th>SYMBOL</th>
                    <th>LICZNIK</th>
                    <th>PALIWO</th>
                    <th>DATA</th>
                </tr>
            </thead>
            <tbody>
                {% for licz in liczniki %}
                    <tr>
                        <td>{{ licz.ID_DYS }}</td>
                        <td>{{ licz.SYMBOL }}</td>
                        <td>{{ licz.TOTAL }}</td>
                        <td>{{ licz.ARTYKUL }}</td>
                        <td>{{ licz.KIEDY }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

lezajsk/templates/lezajsk/liczniki.html
{% extends 'lezajsk/base2.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block styles %}{% endblock %}
{% block title %}Liczniki{% endblock %}
{% block content %}
    <div class="container">
        <h2>Liczniki Leżajsk</h2>

        <div class="row">
            <div class="col-md-9">
                <form>
                    <input type="text" id="qq" name="qre">
                    <input type="submit" value="search" class="btn btn-outline-primary">
                </form>
                <a type="button" class="btn btn-primary" href="{% url 'lezajsk:add_liczniki' %}">Dodaj Dostawę</a>

                <div>
                    <table class="table table-sm table-striped">
                        <thead>
                            <tr>
                                <th>NUMER DYST</th>
                                <th>NUMER WĘŻA</th>
                                <th>SYMBOL</th>
                                <th>LICZNIK</th>
                                <th>PALIWO</th>
                                <th>DATA</th>
                                <th>DATA WGRANIA</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for licz in liczniki %}
                            <tr>
                                <td>{{ licz.ID_DYS }}</td>
                                <td>{{ licz.ID_WAZ }}</td>
                                <td>{{ licz.SYMBOL }}</td>
                                <td>{{ licz.TOTAL }}</td>
                                <td>{{ licz.ARTYKUL }}</td>
                                <td>{{ licz.KIEDY }}</td>
                                <td>{{ licz.KIEDY_WGR }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

lezajsk/templates/lezajsk/liczniki_add.html
{% extends 'lezajsk/base2.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block styles %}{% endblock %}
{% block title %}Save Dostawy{% endblock %}
{% block content %}
    <div class="container">
        <h2>Dodaj dostawę + Liczniki (Leżajsk)</h2>
        <div class="row">
            <div class="col-sm-6">
                    <table class="table table-sm table-striped">
                        <tr>
                            <th>NUMER DYST</th>
                            <th>SYMBOL</th>
                            <th>LICZNIK</th>
                            <th>DATA LICZ</th>
                        </tr>
                    {% for licz in liczniki %}
                        <tr>
                            <td>{{ licz.ID_DYS }}</td>
                            <td>{{ licz.SYMBOL }}</td>
                            <td>{{ licz.TOTAL }}</td>
                            <td>{{ licz.KIEDY }}</td>
                        </tr>
                    {% endfor %}
                    </table>
                </div>
                <div class="col-sm-4">
                    {% crispy form %}
                </div>
        </div>
    </div>
{% endblock %}

lezajsk/templates/lezajsk/list_dostawy.html
{% extends 'lezajsk/base2.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block styles %}{% endblock %}
{% block title %}Dostawy{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-9">
            <div class="messages">
                        {% if messages %}
                        {% for message in messages %}
                        <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

                        </div>
                        {% endfor %}
                        {% endif %}
            </div>
            <h2>Lista zapisanych dostaw z licznikami Leżajsk</h2>
            <ul class="list-group">
                {% for list in lista %}
                    <li class="list-group-item"><a class="list-group-item list-group-item-action list-group-item-primary"
                                                   href="{% url 'lezajsk:details_dost' list.number %}">
                        Dostawa {{ list.created }} ({{ list.number }}) - ({{list.dostawca}})</a>
                    </li>
                {% endfor %}
            </ul>
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    {% if lista.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                    <li class="page-item"><a class="page-link"href="?page={{ lista.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                    <li class="page-item disabled"><a class="page-link" href="?page=1">First</a></li>
                    <li class="page-item disabled"><a class="page-link"href="">&laquo;</a></li>
                    {% endif %}
                    <li class="page-item active">
                        <span class="page-link">Page {{ lista.number }} of {{ lista.paginator.num_pages }}.</span></li>
                    {% if lista.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ lista.next_page_number }}"> &raquo;</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ lista.paginator.num_pages }}">Last</a></li>
                    {% else %}
                    <li class="page-item disabled"><a class="page-link" href=""> &raquo;</a></li>
                    <li class="page-item disabled"><a class="page-link" href="?page={{ lista.paginator.num_pages }}">Last</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
{% endblock %}