armii/urls.py
from django.urls import path, include
from .views import licz_list, handle_licz, dostawy_list, dostawy_details, edit_dostawy, LicznikBazowyArmiiViewSet
from rest_framework import routers
from .api import UserAuthentication


router = routers.DefaultRouter()
router.register(r'liczniki', LicznikBazowyArmiiViewSet)


app_name = "armii"
urlpatterns = [
    path('liczniki/', licz_list, name="liczniki"),
    path('dost/', dostawy_list, name="dost_armii"),
    path('api/', include(router.urls)),
    path('api/auth/', UserAuthentication.as_view(), name="UserAuth"),
    path('liczniki/add/', handle_licz, name="add_liczniki"),
    path('dost/<int:stany_id>/', dostawy_details, name="details_dost"),
    path('dost/<int:stany_id>/edit/', edit_dostawy, name="edit_dost"),
]

dostawy/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('okulickiego/', include('okulickiego.urls')),
    path('rudna/', include('rudna.urls')),
    path('armii/', include('armii.urls')),
    path('wola/', include('wola.urls')),
    path('rzecha/', include('rzecha.urls')),
    path('sikorskiego/', include('sikorskiego.urls')),
    path('ostrow/', include('ostrow.urls')),
    path('lezajsk/', include('lezajsk.urls')),
    path('jaroslaw/', include('jaroslaw.urls')),
    path('podkarpacka/', include('podkarpacka.urls')),
    path('jasionka/', include('jasionka.urls')),
    path('warszawska/', include('warszawska.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('register.urls')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon/favicon.ico'))),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path
from .views import home, about, contact, user_profile


urlpatterns = [
    path('', home, name="home"),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('user/<int:user_id>/profile/', user_profile, name='userprofile'),
]

ostrow/urls.py
from django.urls import path, include
from .views import licz_list, handle_licz, dostawy_list, dostawy_details, edit_dostawy, LicznikBazowyOstrowViewSet
from rest_framework import routers
from .api import UserAuthentication


router = routers.DefaultRouter()
router.register(r'liczniki', LicznikBazowyOstrowViewSet)


app_name = "ostrow"
urlpatterns = [
    path('liczniki/', licz_list, name="liczniki"),
    path('dost/', dostawy_list, name="dost_ostrow"),
    path('api/', include(router.urls)),
    path('api/auth/', UserAuthentication.as_view(), name="UserAuth"),
    path('liczniki/add/', handle_licz, name="add_liczniki"),
    path('dost/<int:stany_id>/', dostawy_details, name="details_dost"),
    path('dost/<int:stany_id>/edit/', edit_dostawy, name="edit_dost"),
]

rudna/urls.py
from django.urls import path, include
from .views import licz_list, handle_licz, dostawy_list, dostawy_details, edit_dostawy, LicznikBazowyRudnaViewSet
from rest_framework import routers
from .api import UserAuthentication


router = routers.DefaultRouter()
router.register(r'liczniki', LicznikBazowyRudnaViewSet)


app_name = "rudna"
urlpatterns = [
    path('liczniki/', licz_list, name="liczniki"),
    path('dost/', dostawy_list, name="dost_rudna"),
    path('api/', include(router.urls)),
    path('api/auth/', UserAuthentication.as_view(), name="UserAuth"),
    path('liczniki/add/', handle_licz, name="add_liczniki"),
    path('dost/<int:stany_id>/', dostawy_details, name="details_dost"),
    path('dost/<int:stany_id>/edit/', edit_dostawy, name="edit_dost"),
]

wola/urls.py
from django.urls import path, include
from .views import licz_list, handle_licz, dostawy_list, dostawy_details, edit_dostawy, LicznikBazowyWolaViewSet
from rest_framework import routers
from .api import UserAuthentication


router = routers.DefaultRouter()
router.register(r'liczniki', LicznikBazowyWolaViewSet)


app_name = "wola"
urlpatterns = [
    path('liczniki/', licz_list, name="liczniki"),
    path('dost/', dostawy_list, name="dost_wola"),
    path('api/', include(router.urls)),
    path('api/auth/', UserAuthentication.as_view(), name="UserAuth"),
    path('liczniki/add/', handle_licz, name="add_liczniki"),
    path('dost/<int:stany_id>/', dostawy_details, name="details_dost"),
    path('dost/<int:stany_id>/edit/', edit_dostawy, name="edit_dost"),
]

main/models.py
from django.db import models


class UserProfile(models.Model):
    user = models.OneToOneField("auth.User", on_delete=models.CASCADE)
    bio = models.TextField()

main/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, HTML
from django import forms

from main.models import UserProfile


class ContactForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    title = forms.CharField()
    content = forms.CharField(widget=forms.Textarea)
    send_to_me = forms.BooleanField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_action = 'contact'
        self.helper.layout = Layout(
            Fieldset(
                'Dane kontaktowe',
                'email',

            ),
            Fieldset(
                'Zawartość',
                'title',
                'content'
            ),
            Fieldset(
                'Dodatkowe',
                HTML("Zaznacz jeśli chcesz by wysłać kopię wiadomości do Ciebie"),
                'send_to_me'
            ),
            ButtonHolder(
                Submit('submit', 'Wyślij', css_class='btn btn-primary'),
                css_class="d-flex justify-content-end"
            )
        )


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['user', 'bio']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_action = 'profile'
        self.helper.add_input(Submit('submit', 'Wyślij'))

main/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .forms import ContactForm, UserProfileForm
from . import services
from django.urls import reverse


def home(request):
    return render(request, "main/index.html")


@login_required
def about(request):
    return render(request, "main/about.html", {})


@login_required
def contact(request):
    if request.method == "POST":
        form = ContactForm(data=request.POST)
        if form.is_valid():
            services.send_message(form.cleaned_data)
    else:
        form = ContactForm()

    return render(request, 'main/contact.html', {"form": form})


def user_profile(request, user_id):
    user = get_object_or_404(get_user_model(), id=user_id)
    if request.method == 'post':
        try:
            profile = user.userprofile
            form = UserProfileForm(request.POST, instance=profile)
        except AttributeError:
            pass
        if form.is_valid():
            form.save()
    else:
        try:
            profile = user.userprofile
            form = UserProfileForm(instance=profile)
        except AttributeError:
            form = UserProfileForm(initial={"user": user, "bio": ""})
        if request.user != user:
            for field in form.fields:
                form.fields[field].disabled = True
            form.helper.inputs = []
    return render(request, 'main/userprofile.html', {'form': form})

main/templates/main/about.html
{% extends 'base.html' %}
{% block title %}O nas{% endblock %}
{% block nav %}
    <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a class="nav-link px-2 link-secondary" href="{% url 'home' %}">Strona główna</a></li>
    </ul>
{% endblock %}
{% block content %}
    <h1>O projekcie</h1>
{% endblock %}

main/templates/main/contact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Kontakt{% endblock %}
{% block nav %}
    <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a class="nav-link px-2 link-secondary" href="{% url 'home' %}">Strona główna</a></li>
    </ul>
{% endblock %}
{% block content %}
    {% crispy form %}
{% endblock %}

main/templates/main/index.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %}Home{% endblock %}
{% block styles %}{% endblock %}
{% block content %}
    {% thumbnail "main/img/cystern.png" "480x216" as im %}
        <div class="d-flex flex-wrap align-items-center justify-content-center mb-2">
            <img src="{{ im.url }}">
        </div>
    {% endthumbnail %}
    {% if user.is_authenticated %}
        <div class="row">
            <div class="col-md-9">
                <ul class="list-group">
                    {% if perms.okulickiego.view_dostawaokulickiego %}
                    <li class="list-group-item"><a
                            class="list-group-item list-group-item-action list-group-item-primary"
                            href="{% url 'okulickiego:dost_okuli' %}">Okulickiego</a></li>
                    {% endif %}
                    {% if perms.rudna.view_dostawarudna %}
                    <li class="list-group-item"><a
                            class="list-group-item list-group-item-action list-group-item-primary"
                            href="{% url 'rudna:dost_rudna' %}">Rudna</a></li>
                    {% endif %}
                    {% if perms.wola.view_dostawawola %}
                    <li class="list-group-item"><a
                            class="list-group-item list-group-item-action list-group-item-primary"
                            href="{% url 'wola:dost_wola' %}">Wola</a></li>
                    {% endif %}
                    {% if perms.armii.view_dostawaarmii %}
                    <li class="list-group-item"><a
                            class="list-group-item list-group-item-action list-group-item-primary"
                            href="{% url 'armii:dost_armii' %}">Armii</a></li>
                    {% endif %}
                    {% if perms.rzecha.view_dostawarzecha %}
                    <li class="list-group-item"><a
                            class="list-group-item list-group-item-action list-group-item-primary"
                            href="{% url 'rzecha:dost_rzecha' %}">Rzecha</a></li>
                    {% endif %}
                    {% if perms.sikorskiego.view_dostawasikorskiego %}
                    <li class="list-group-item"><a
                            class="list-group-item list-group-item-action list-group-item-primary"
                            href="{% url 'sikorskiego:dost_sikorskiego' %}">Sikorskiego</a></li>
                    {% endif %}
                    {% if perms.ostrow.view_dostawaostrow %}
                    <li class="list-group-item"><a
                            class="list-group-item list-group-item-action list-group-item-primary"
                            href="{% url 'ostrow:dost_ostrow' %}">Ostrów</a></li>
                    {% endif %}
                    {% if perms.lezajsk.view_dostawalezajsk %}
                    <li class="list-group-item"><a
                            class="list-group-item list-group-item-action list-group-item-primary"
                            href="{% url 'lezajsk:dost_lezajsk' %}">Leżajsk</a></li>
                    {% endif %}
                    {% if perms.jaroslaw.view_dostawajaroslaw %}
                    <li class="list-group-item"><a
                            class="list-group-item list-group-item-action list-group-item-primary"
                            href="{% url 'jaroslaw:dost_jaroslaw' %}">Jarosław</a></li>
                    {% endif %}
                    {% if perms.podkarpacka.view_dostawapodkarpacka %}
                    <li class="list-group-item"><a
                            class="list-group-item list-group-item-action list-group-item-primary"
                            href="{% url 'podkarpacka:dost_podkarpacka' %}">Podkarpacka</a></li>
                    {% endif %}
                    {% if perms.jasionka.view_dostawajasionka %}
                    <li class="list-group-item"><a
                            class="list-group-item list-group-item-action list-group-item-primary"
                            href="{% url 'jasionka:dost_jasionka' %}">Jasionka</a></li>
                    {% endif %}
                    {% if perms.warszawska.view_dostawawarszawska %}
                    <li class="list-group-item"><a
                            class="list-group-item list-group-item-action list-group-item-primary"
                            href="{% url 'warszawska:dost_warszawska' %}">Warszawska</a></li>
                    {% endif %}

                </ul>
            </div>
        </div>
    {% endif %}
{% endblock %}

main/templates/main/userprofile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Profil{% endblock %}
{% block content %}
{% crispy form %}
{% endblock %}